site_name: Fantasy Basketball Optimization, Methods & Documentation
nav:
  - Home: index.md
  - Settings : settings.md
  - Parameters : parameters.md
  - G-scores : gscores.md
  - H-scores : hscores.md
  - Rotisserie : roto.md
  - Draft Mode : drafts.md
  - Auction Mode : auctions.md 
  - Season Mode : season.md
  - Projection Adjustment : projectionadjustment.md
theme: 
  name : material
  favicon: img/favicon.ico
markdown_extensions:
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js